Sofia
RobomasterOwltech/deployTools pull request #2
Opened 2024-07-11 18:23 UTC by sofiaariasv2002

comente el chupon. 
Realice una funcion para instalar docker en caso que no se tenga.
instalar paquetes runc y container
Corregir el if.

2024-07-12 03:30 UTC, JorgePerC requested changes
Te dejé unos cambios :)

2024-07-12 03:30 UTC, JorgePerC commented on initialSetup/runMeUbuntu.sh
> +        if [[ "$1" == *ubuntu* ]]; then
Para qué los asteriscos?

2024-07-12 03:30 UTC, JorgePerC commented on initialSetup/runMeUbuntu.sh
> +    sudo apt -y install "$app"
Antes del install, sería buena idea hacer el update/upgrade

2024-07-12 03:30 UTC, JorgePerC commented on initialSetup/runMeUbuntu.sh
> +#echo "      `-._,-'"
Puedes poner que use el encoding en_US.UTF-8 durante el script?

2024-07-12 03:30 UTC, JorgePerC commented on initialSetup/runMeUbuntu.sh
> +sudo apt-get --fix-missing install runc
Sería bueno que pusieras esto en la parte de arriba, donde viene la lista de paquetes

2024-07-12 03:34 UTC, JorgePerC commented on initialSetup/runMeUbuntu.sh
> +sudo apt-get --fix-missing install runc
Además, en este caso se está asociando apt con ubuntu

2024-07-12 17:38 UTC, sofiaariasv2002 commented on initialSetup/runMeUbuntu.sh
> +        if [[ "$1" == *ubuntu* ]]; then
Porque con asteriscos sirve para verificar que la palabra este dentro del texto aunque el texto no sea solo ubuntu y con comillas es para forma literal, si es un texto y no solo la palabra ubuntu lo considera como falso

2024-07-12 18:17 UTC, JorgePerC commented on initialSetup/runMeUbuntu.sh
> +        if [[ "$1" == *ubuntu* ]]; then
Y esa función donde se está llamando? 👁️ 👄 👁️

2024-07-12 18:19 UTC, sofiaariasv2002 commented on initialSetup/runMeUbuntu.sh
> +        if [[ "$1" == *ubuntu* ]]; then
installDependencies "ubuntu"; 
ya lo cambie pero haria lo mismo com * o "
:)

2024-07-13 15:43 UTC, JorgePerC approved these changes
Arre 🤠

2024-07-13 15:44 UTC, merged